[package]
name = "dino-park-fence"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[dependencies]
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", features = ["graphql", "aws"] }
actix = "0.7"
actix-web = "0.7"
juniper = "0.11.1"
futures = "0.1"
log = "0.4"
env_logger = "0.6"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
reqwest = "0.9.8"
url = "1.7.2"
chrono = "0.4.6"
biscuit = "0.1.0"
percent-encoding = "1.0"
