[package]
name = "dino-park-fence"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[dependencies]
condvar_store = { git = "https://github.com/fiji-flo/condvar_store" }
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", features = ["graphql", "aws", "vendored"] }
cis_client = { git = "https://github.com/fiji-flo/cis_client-rust" }
actix = "0.7"
actix-web = "0.7"
juniper = "0.11.1"
futures = "0.1"
log = "0.4"
env_logger = "0.6"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
reqwest = "0.9"
chrono = "0.4"
biscuit = "0.1.0"
percent-encoding = "1.0"
config = "0.9"
